apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-repo-deployment
  labels:
    app: private-repo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-repo-pod
  template:
    metadata:
      labels:
        app: private-repo-pod
    spec:
      containers:
        - name: private-repo-container
          image: krishnabelamkonda/secret-repo:k8s_github_v6
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
