apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
  labels:
    app: postgres-database
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres-database
  template:
    metadata:
      labels:
        db: postgres-database
    spec:
      containers:
        - name: postgres-db-container
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-db-secret
                  key: db_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: psql-db-secret
                  key: db_name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-db-secret
                  key: db_pass
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: psql-db-secret
#                  key: db_user





#$ docker run --name some-postgres -e POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd -d postgres
#POSTGRES_INITDB_ARGS, POSTGRES_PASSWORD, POSTGRES_USER, and POSTGRES_DB
