apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
spec:
  type: NodePort
  selector:
    db: postgres-database
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5432
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30032

#kubectl run test-client --rm -it --image=postgres:14 --namespace=<namespace> -- \
#    psql -h postgres-service -U <username> -d <database>

#kubectl run test-client --rm -it --image=postgres:14 --namespace=database -- \
#    psql -h postgres -U krishna -d demo-db
