apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-app-pv
  labels:
    type: local
spec:
  storageClassName: flaskapp-pv-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
