apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-pv-claim
spec:
  storageClassName: flaskapp-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
    limits:
      storage: 1Gi
