apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configs
  labels:
    name: database-configs
  # this will be created in the given namespace
  # if the namespace is
  # 1. not specified: default will be used
  # 2. given namespace if not available, It'll raise an error
#  namespace: common
data:
  DBNAME: "krishna"
  DBHOST: "localhost"  # Before
#  DBHOST: "MyHost"  # After
  DBUSER: "King"
  DBPASSWORD: "Password"
