apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-cm  #cm-configmaps
spec:
  containers:
    - name: flask-app
      image: krishnabelamkonda/test-repo:k8s_github
      ports:
      - containerPort: 5000
      env:
        - name: DATABASE_NAME  # environment variable name
          valueFrom:
            configMapKeyRef:
              name: db-configs  # configmap file name
              key: DBNAME  # key from the given configmap

        - name: DATABASE_HOST  # environment variable name
          valueFrom:
            configMapKeyRef:
              name: db-configs  # configmap file name
              key: DBHOST  # key from the given configmap

        - name: DATABASE_USER  # environment variable name
          valueFrom:
            configMapKeyRef:
              name: db-configs  # configmap file name
              key: DBUSER  # key from the given configmap

        - name: DATABASE_PASSWORD  # environment variable name
          valueFrom:
            configMapKeyRef:
              name: db-configs  # configmap file name
              key: DBPASSWORD  # key from the given configmap
