apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: gopi
type: Opaque
data:
  #  We can use any mode of encryption, in this example I used base64
  #  The below value is for GopiKrishna
  #  it's base64 encoded,
  #  echo -n 'GopiKrishna' | base64
  username: R29waUtyaXNobmE=
  #  The below value is for Belamkonda
  #  it's base64 encoded,
  #  echo -n 'Belamkonda' | base64
  password: QmVsYW1rb25kYQ==
